### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by IshanKuber** [Arin-Torney/mylogo#3]
I won't suggest any pull request but I assure that there is a problem

**Comment by Arin-Torney** [comment]
Please tell what is the problem.

**Comment by IshanKuber** [comment]
Hey there! Thank you for reaching out to me for solution. I think you should be using split(" ") method in the program to make it user friendly. Because when I tried it first of all I didn't even get it how to use it. But then I found out this problem....

**Comment by Arin-Torney** [comment]
OK
It is a bit difficult as I don't know the method still I may try it.
Thanks for your suggestion.
:+1::+1:
